### ISSUE TITLE
UOP & Missing Animations

### ISSUE THREAD

**Issue by Nirad** [crossuo/crossuo#1]
UOP format is not fully understood, consequently some animations are missing

**Comment by fungos** [comment]
Probably fixed by https://github.com/crossuo/crossuo/commit/4fc2fdade128884617257bbbc83ee7de771528c6 but it seems there is still some unsupported uop animations, need double check.

**Comment by Krubster** [comment]
Tiger animation looks weird and z-offset is wrong
![изображение](https://user-images.githubusercontent.com/46751971/54305361-366ee300-45d8-11e9-907c-19423438aaf4.png)

**Comment by Vlek** [comment]
This is a serious PITA for UO Outlands. They have so many custom animations that aren't properly showing up and monsters can disappear and/or are showing as incorrect z.

For shards without customizations, I know that this is an issue with the ogre graphic.
