### ISSUE TITLE
Cannot raise, lower or lock attributes

### ISSUE THREAD

**Issue by calemccammon** [crossuo/crossuo#102]
![status](https://user-images.githubusercontent.com/16568056/59570920-f99a0880-906c-11e9-9325-03569782e334.png)
OS: Windows 10 64 bit
Version: latest nightly
Server: OSI

Steps:
1. Open paperdoll
2. Click status
3. Observe status menu:

The classic client has arrows to the left of each attribute which allow you to lower, raise, or lock the attribute. There are no arrows with CrossUO.

**Comment by Nirad** [comment]
can you provide me a screenshot of the classic client?

**Comment by calemccammon** [comment]
![CC](https://user-images.githubusercontent.com/16568056/62401992-9e0bd780-b553-11e9-8ed8-68260fb76f21.PNG)

**Comment by Nirad** [comment]
@calemccammon thx

**Comment by Nirad** [comment]
![Capture d’écran 2019-08-02 à 22 37 07](https://user-images.githubusercontent.com/359353/62406216-2d29e700-b576-11e9-96c7-0c7161f350de.png)

**Comment by fungos** [comment]
Not an issue on master. Reopen if there is are better repro steps.
