### ISSUE TITLE
Aos menu - SphereSvr-X

### ISSUE THREAD

**Issue by FiLoUs64** [crossuo/crossuo#104]
## Description

Impossible to see AoS menu when you one click on a character.

Works fine on Sphere 56d

Works with Classic Client

## Environment

* CrossUO version: 1.0.2 (be5bd9bf)
* Operating System: e.g. Windows 10
* Server Info: SphereServer X
* Server Address: ask for test

![unknown](https://user-images.githubusercontent.com/47130805/60932611-d4c03c00-a28c-11e9-875d-ad12c48e253f.png)

**Comment by Nirad** [comment]
Are you sure its a CrossUO bug ? send me address to a test server plz on discord

**Comment by FiLoUs64** [comment]
Yes, works with Classic Client. Updated issue description.

**Comment by Nirad** [comment]
all work good Sphere-X bug close this issue
![Capture d’écran 2019-07-09 à 21 29 53](https://user-images.githubusercontent.com/359353/60933546-b8be9980-a290-11e9-812c-88fa0bb441b9.png)

**Comment by FiLoUs64** [comment]
After testing, first login don't work, just relog and it work
