### ISSUE TITLE
Life % over the head of player

### ISSUE THREAD

**Issue by Jhobean** [crossuo/crossuo#107]
![image](https://user-images.githubusercontent.com/51728381/61883796-14139d00-aec9-11e9-8eb5-8a7fdb6c3bb9.png)

## Description

When I choose the option to show %of life, nothing appear.

## Environment

* CrossUO version: last
* Operating System: Windows 10
* Server Info: sphereSVR

**Comment by calemccammon** [comment]
Your screenshot shows that you have No Draw enabled. You would need to select either Above Character or Under Character.

**Comment by Jhobean** [comment]
Ok i'll try.  I think you are right.:relaxed:
