### ISSUE TITLE
Unable to start UO client on MacOS 10.14.6

### ISSUE THREAD

**Issue by wondris009** [crossuo/crossuo#109]
## Description

I setup UO through WineHQ. I can click client.exe and game normally starts. When i try that using crossuo mac client i can see this message in console "nw_path_close_fd Failed to close guarded necp fd 17 [9: Bad file descriptor]" 

## Environment

* CrossUO version: latest
* Operating System: MacOS Mojave 10.14.6
* Server Address: server.uoerebor.cz,2599
* Server Account Creation: auto-account, account creation url, etc.

**Comment by Nirad** [comment]
UO Version ?

**Comment by wondris009** [comment]
UO version 7.0.76.4 (Patch unknown)
