### ISSUE TITLE
Screen is stuck on "Verifying account" after logging in

### ISSUE THREAD

**Issue by sfxpok** [crossuo/crossuo#110]
## Description

After launching the client and entering my user credentials, the UO screen is stuck with the text "Verifying account".

## Repro steps

Some screenshots regarding the issue:

Client:

https://i.imgur.com/VT3VE11.png

Launcher settings:

https://i.imgur.com/RzwkXXM.png

https://i.imgur.com/tzNQL9U.png

## Environment

* CrossUO version: 1.0.0 (276195a)
* Operating System: Ubuntu 19.04
* Server Info: Don't know
* Server Address: pangaea-world.ddns.net,5003
* Server Account Creation: Can't recall

**Comment by calemccammon** [comment]
@sfxpok try checking Use Crypt

**Comment by sfxpok** [comment]
that doesn't work @calemccammon

**Comment by fungos** [comment]
Based on your screenshot, I think the issue is your server address. There is a space after the comma, try removing it.

**Comment by sfxpok** [comment]
@fungos that doesn't fix the issue

**Comment by fungos** [comment]
Normally when that happens, it means the server is unreachable. So, if the space didn't change anything, this means the server is unreachable. Is this the shard? http://pangaea-world.dk/ I would suggest you to double check the address with them. *ddns.net* seems a bit problematic for a freeshard anyway.

**Comment by Backlund** [comment]
I downloaded the Pangaea client, but i don't have an account so i just typed test/test.
But the same thing happen to me, so either its the pangaea client or the server is unreachable

**Comment by calemccammon** [comment]
The shard has a particular set up for logging in as well, which is more involved than just creating your account directly from the login screen: http://pangaea-world.dk/pangaea/faq/logging-in

**Comment by Backlund** [comment]
Oh, didn't see that. But crossuo is looking for client.exe, right? Should I rename the "No_Crypt_Client_2d.exe" if I should try again?

**Comment by calemccammon** [comment]
You could try that, but you may not be able to actually log in since it looks like game accounts are registered through the website. Also you should make sure the client version is correct in the launcher.

**Comment by Backlund** [comment]
So, I don't think we can call this a crossuo bug?

**Comment by Nirad** [comment]
we can close ?

**Comment by Backlund** [comment]
It's not really up to me, but I don't think it is a crosuo bug. It seems like it don't can connect to the server, but it is a "special" client, and I don't think it is officially supported by crossuo.
So I would say it's not a crossuo bug.
