### ISSUE TITLE
Discolored server list

### ISSUE THREAD

**Issue by calemccammon** [crossuo/crossuo#117]
CrossUO latest nightly: https://ci.appveyor.com/project/fungos/crossuo/builds/27675561/job/vljdhwl6xcfrqghl/artifacts
OS: Windows 10 64 bit
Server: OSI
Client: 7.0.79.6

1. Launch and sign in
2. Observe server list is discolored
![Capture](https://user-images.githubusercontent.com/16568056/65735632-14394000-e0a6-11e9-91a2-8ae329923df8.PNG)

**Comment by Nirad** [comment]
Can you test the nightly should be ok now
