### ISSUE TITLE
Draggable Gumps not draggable

### ISSUE THREAD

**Issue by popoverde** [crossuo/crossuo#137]
## Description

I made a custom gump, it shows some custom images, its draggable, but CUO doesnt let me drag it

Im using client 6.0.0.0  runuo 2.2

it allso happens with a very small gump that only send an image.

**Comment by Nirad** [comment]
You mean yo are not able to move the Gump ?

**Comment by popoverde** [comment]
exactly, a draggable gump cant be moved

**Comment by Nirad** [comment]
can you try the nightly ? Gump move on my side ..

**Comment by fungos** [comment]
Can't reproduce. If the issue still happens and you have a sample test case on an accessible shard, reopen this issue.
