### ISSUE TITLE
New Boat command Patch 86

### ISSUE THREAD

**Issue by Nirad** [crossuo/crossuo#15]
https://uo.com/wiki/ultima-online-wiki/publish-notes/publish-86/
Boat commands:
Added target boat wheel (it works like the mount actions)
Added several missing commands: slow back/forward, forward/back one and start/stop tracking Classic Client 7.0.35
9/25/2014

We can check POL implemention here : https://github.com/polserver/polserver/blob/9cfb4ec5a5886fd8277770bd8323101835ba26ac/pol-core/pol/multi/boat.cpp#L358

and ClasicUO implementation here : https://github.com/andreakarasho/ClassicUO/blob/master/src/Network/PacketHandlers.cs#L2473-L2504

In our project :
https://github.com/OrionUO/OrionUO/blob/master/OrionUO/Managers/PacketManager.cpp#L6693

**Comment by Nirad** [comment]
![capture d ecran 2019-02-17 a 20 25 09](https://user-images.githubusercontent.com/359353/52935815-6a801c80-3328-11e9-90d0-fafc228e0f77.png)

![capture d ecran 2019-02-17 a 20 27 50](https://user-images.githubusercontent.com/359353/52935782-5805e300-3328-11e9-80b6-83d46c6becc4.png)

**Comment by Nirad** [comment]
not perfect ;)

**Comment by AimedNuu** [comment]
@Nirad Classic UO Implementation here: https://github.com/andreakarasho/ClassicUO/blob/761fb0768e30de50243cc72801dbdd4e040bf20a/src/Network/PacketHandlers.cs#L3220-L3264
Not sure if it's fully implemented though.
