### ISSUE TITLE
Book of Masteries

### ISSUE THREAD

**Issue by Deadthing** [crossuo/crossuo#153]
![uoissue1](https://user-images.githubusercontent.com/59266535/71492067-8edb3e00-2802-11ea-8f5f-aa4538ef1b24.png)
![uoissue2](https://user-images.githubusercontent.com/59266535/71492075-9dc1f080-2802-11ea-8e6f-56a6e03701bc.png)

## Description
When trying to open the Mastery Spellbook, the Magery Spellbook is opened instead. First Screen is from the Classic Client, showing the correct tooltip and correct spellbook open. Second screen is from Cross UO, showing the correct tooltip, but incorrect spellbook open. 

## Environment

* CrossUO version: 1.01
* Operating System:Windows 10
* Server Info: Retail Servers
* Server Address: 107.23.176.74,7775 (one of 4)
* Server Account Creation: Website Account Creation

**Comment by Nirad** [comment]
wow ok i iiil look at it...

**Comment by Deadthing** [comment]
Small update: I noticed that spellbook being opened when I use the Mastery Book is NOT one of the spellbooks I'm carying. It opens a phantom (for lack of a better word) spellbook with only circles 1-5 and about half of circle 6 in it.
