### ISSUE TITLE
Improve and rename GumpToolbar

### ISSUE THREAD

**Issue by fungos** [crossuo/crossuo#161]
Current `GumpToolbar` implementation is missing some features:
- Close button
- Open macro / Open option
- Save/Restore position on user profile 

Also, we should rename this into `GumpResourceTracker`

**Comment by Nirad** [comment]
👍

**Comment by fungos** [comment]
Done.
![image](https://user-images.githubusercontent.com/151544/96319674-5ea59b80-0fde-11eb-8c24-1ea943f80e34.png)
