### ISSUE TITLE
incorrect picture of reagents from the merchant and other items

### ISSUE THREAD

**Issue by sharabdin1988** [crossuo/crossuo#186]
## Description
<img width="736" alt="bag" src="https://user-images.githubusercontent.com/38672017/75619884-9b796b00-5b92-11ea-9691-f8ef0c174358.png">

## Environment

* CrossUO version: e.g. 1.0.1
* Operating System: e.g. MacOS Catalina 10.15.3
* Server Info: POL 99
* Server Address: 93.188.40.121,5005
* Server Account Creation:  account creation url http://middle-earth.ru/?menu=start

**Comment by Nirad** [comment]
![Capture d’écran 2020-07-07 à 18 51 44](https://user-images.githubusercontent.com/359353/86852528-eea08480-c082-11ea-88b1-5eaaef0e478c.png)

**Comment by Nirad** [comment]
all good here
