### ISSUE TITLE
Character position on pop-out map is incorrect

### ISSUE THREAD

**Issue by Vlek** [crossuo/crossuo#269]
## Description

The pop-out map that's available for the client will show the player has being in a different position than they are in game.

![Screenshot_from_2020-06-20_14-06-31](https://user-images.githubusercontent.com/15008772/88832060-16b46c80-d185-11ea-8061-5fc884ac4469.png)

## Repro steps

1. Open map in the assistant
1. Select rotate map
1. Open in-game map
1. Notice the difference in the player's location

## Environment

* CrossUO version: v1.0.4 (b173f9d)
* Operating System: Ubuntu 20.04
* Server Info: RunUO 2.7
* Server Address: login.uogamers.com,2593
* Server Account Creation: auto-account, account creation url, etc.

**Comment by Nirad** [comment]
XUOASSIT will be rewritten
