### ISSUE TITLE
[xuolauncher] unknown client: 0x8a195244c1e9c44b, 0xde1de66c, 0x00000000

### ISSUE THREAD

**Issue by keni2006** [crossuo/crossuo#282]
My client version is: Unknown
OS mac os

**Comment by keni2006** [comment]
[client.exe.zip](https://github.com/crossuo/crossuo/files/5345091/client.exe.zip)

**Comment by keni2006** [comment]
Not working, im recompiled crossuo with ur changes, I'm not a programmer, but rather it's due to the fact that the abyss server uses its own encryption or something like that, the point is that you need to force client.exe to load abyss.dll through crossuo,or something like that. The server simply does gave ur permission for entry add-ons like injection,crossuo etc....

**Comment by fungos** [comment]
Yes, Abyss has a custom dll for their protection. We can't support that shard unless someone do the reversing and contribute patches, which I doubt will ever happen. Sorry.
