### ISSUE TITLE
[xuolauncher] unknown client: 0x8e5255b9372a5329, 0x00000000, 0x0700570b

### ISSUE THREAD

**Issue by kirill-stepanoff** [crossuo/crossuo#287]
My client version is: Ultima Online Classic 7.0.87.11 
OS Ubuntu 20.10 kernel 5.8.0-26 

STR:
1. Download client via link from uo.com:
 http://web.cdn.eamythic.com/us/uo/installers/20120309/UOClassicSetup_7_0_24_0.exe
2. install it using wine
3. update client with running uopatch.exe via wine
4. set the path to installed client in UO Data Path field
5. Press 'Launch' button

**Comment by fungos** [comment]
Fixed here https://github.com/crossuo/crossuo/commit/1d53f78f1bd716b356e254e2d6de0ca25c3de163
Waiting for a release update
