### ISSUE TITLE
Still does not compile

### ISSUE THREAD

**Issue by txtsd** [crossuo/crossuo#295]
## Description
Does not compile after the last commit
Log: https://0x0.st/-zCk.log

## Repro steps
Run `cmake -B build && cmake --build build`

## Environment

* CrossUO version: e44fe3990ac718cbe593ade7847568f98ee3bbf3
* Operating System: Arch Linux
* Server Info: -
* Server Address: -
* Server Account Creation: -

**Comment by fungos** [comment]
was your cmake cache clean?
> WAYLAND_SHARED         (Wanted: ON): ON

This should be disabled, try this way:

`cmake -B build && cmake --build build -DWAYLAND_SHARED=Off`

**Comment by txtsd** [comment]
> was your cmake cache clean?

Yes I deleted the build folder before running it.

**Comment by fungos** [comment]
This new commit should fix that, give another try please.

**Comment by txtsd** [comment]
It builds now. Thank you!
