### ISSUE TITLE
[xuolauncher] unknown client: 0xe6df8e7b272b6a3e, 0x00000000, 0x07005801\

### ISSUE THREAD

**Issue by XenokronWicked** [crossuo/crossuo#297]
My client version is: (7.0.88.1)
[client.zip](https://github.com/crossuo/crossuo/files/6017115/client.zip)
(please, upload your client.exe with a screenshot and link here to help further)

**Comment by fungos** [comment]
Thank you, fixed in the main. A new release will be available to download [here](https://github.com/crossuo/crossuo/releases/tag/master) shortly.
