### ISSUE TITLE
Reward Gump text missing

### ISSUE THREAD

**Issue by JulienThink** [crossuo/crossuo#31]
## Description

There is missing text into Reward Gump
![rewardgump](https://user-images.githubusercontent.com/37397739/52185536-c2932b00-2820-11e9-8778-e4d6d38d7144.png)

[logMissingTextRewardsGump.txt](https://github.com/crossuo/crossuo/files/2826199/logMissingTextRewardsGump.txt)

## Environment

* CrossUO version: e.g. 1.0,0.0 build from code at ClientVersion=7.0.74.28
* Operating System: Windows 10
* Server Info: EA/OSI
* Server Address: login.ultimaonline.com,7776

**Comment by Nirad** [comment]
@JulienThink i am sure 12afba4a19117831dee221e0c28d08372200c81b fix this problem to if you can confirm.

**Comment by Nirad** [comment]
fixed ..
