### ISSUE TITLE
Cu Sidhe bad Z

### ISSUE THREAD

**Issue by JulienThink** [crossuo/crossuo#35]
Hi,
character seat on bad Z axis i think

![cusidhe](https://user-images.githubusercontent.com/37397739/52354160-36efe900-2a30-11e9-8306-9a3276eac5af.png)

**Comment by Nirad** [comment]
![capture d ecran 2019-02-13 a 05 41 59](https://user-images.githubusercontent.com/359353/52706458-7b5d1680-2f53-11e9-9799-9cbde69fbed5.png)

**Comment by Nirad** [comment]
i have fixed other low mount to plz let me know
