### ISSUE TITLE
Can't open gift Box 

### ISSUE THREAD

**Issue by JulienThink** [crossuo/crossuo#36]
Can't open box:

Server : EA/OSI
CliVer : 7.0.74.28

<a href="https://imgbb.com/"><img src="https://image.ibb.co/nJisdc/missinggump.png" alt="missinggump" border="0"></a>
<a href="https://imgbb.com/"><img src="https://image.ibb.co/nu8NUH/box.png" alt="box" border="0"></a>
ID of bags in picture.

**Comment by Nirad** [comment]
if you can find get the Gump id it's will be helpful
![capture d ecran 2019-02-13 a 18 36 16](https://user-images.githubusercontent.com/359353/52751695-5d78cb80-2fbe-11e9-9cd2-c834dbfd061f.png)

**Comment by Admin-Yukiko** [comment]
Here is the gump art I have for open gift boxes. I hope it is helpful.
Open Box Gump Art
Square Gift Boxes
0x102 - White Box with Gold Ribbon
0x11B - White Box with Blue Ribbon
0x121 - Square Box with Rounded Corners and Pink Interior with Bluish Purple Ribbons

Octagon Gift Box
0x11D - Gold Ribbon

Rectangular Gift Boxes
0x11E - White Gift Box with Verticle Light Grey Stripes with Red Ribbon on Lower Left Side and Top Left Side
0x11F - White Gift Box with Gold "Child Angel" with Gold Ribbon on the Right and Left Sides
0x777A - Brown Box with White Wrapping Paper with Gold Ribbons

Round Gift Box
0x11C - Green Ribbon
0x122 - Round Christmas Gift Box with Red and Green Ribbons and Gold Bells

Heart Shaped Gift Box
0x120 - Red Heart with Red Ribbon

**Comment by Nirad** [comment]
wow thx

**Comment by Admin-Yukiko** [comment]
You are very welcome.

**Comment by Nirad** [comment]
ok we need to see if a better way to do this all the container are actually in data/container.txt
[containers.txt](https://github.com/crossuo/crossuo/files/2863712/containers.txt)
![capture d ecran 2019-02-14 a 02 04 49](https://user-images.githubusercontent.com/359353/52769083-43121280-2ffd-11e9-9474-ca8456e4cb45.png)

**Comment by Nirad** [comment]
and as I see in the screen shot all the screen turn to black in original client ?

**Comment by Nirad** [comment]
You can find hard coded stuff here 
https://github.com/crossuo/crossuo/blob/master/src/CrossUO.cpp#L899
