### ISSUE TITLE
Missing text gump 

### ISSUE THREAD

**Issue by JulienThink** [crossuo/crossuo#37]
Missing text on 'Auction Safe' item:

Server : EA/OSI
CliVer : 7.0.74.28

<a href="https://ibb.co/nCBsBx"><img src="https://preview.ibb.co/iqq8jH/missingtext.png" alt="missingtext" border="0"></a>

[log.txt](https://github.com/Hotride/OrionUO/files/1945054/log.txt)

**Comment by Nirad** [comment]
![capture](https://user-images.githubusercontent.com/359353/52889930-3fdb6b80-3150-11e9-995f-d90f9ef80048.PNG)
