### ISSUE TITLE
Ctrl+Shift is non-functional

### ISSUE THREAD

**Issue by Nirad** [crossuo/crossuo#4]
Object handlers doesn't work. In original client, pressing CTRL+SHIFT show handlers for all objects we can interact with.

It is semi-functional, it seems the feature does not currently work with corpses as the original client do.

**Comment by Nirad** [comment]
![capture d ecran 2019-02-13 a 18 10 19](https://user-images.githubusercontent.com/359353/52750583-a890df80-2fba-11e9-8037-588b2686f51c.png)
what is missing here in this issues ?

**Comment by fungos** [comment]
See the body, it should have one too. This should work on bodies.
