### ISSUE TITLE
Can't sit while an elf (Sphere 56d nightly and X)

### ISSUE THREAD

**Issue by FiLoUs64** [crossuo/crossuo#41]
You can't sit if your body is an elf (c_elf_male or c_elf_female in sphere)

Not a problem with Classic Client.
Working fine on ServUO.

![image](https://user-images.githubusercontent.com/47130805/52612374-5f744a80-2e57-11e9-8323-17c819f7df10.png)

* CrossUO version: 1.0.0
* Operating System: Windows 10
* Server Info: sphere 56d nightly and spheresvrX
* Server Address: Just ask for testing

**Comment by Nirad** [comment]
what is the graphic id ?

**Comment by Admin-Yukiko** [comment]
Elf male graphic is 0x25D
Elf female is 0x25E
