### ISSUE TITLE
Crash when attempting to place multi-item (boat, house, etc).

### ISSUE THREAD

**Issue by linxgws** [crossuo/crossuo#47]
## Description

Game crashes when attempting to place a multi-item (boats, galleons, houses, etc).

## Repro steps

- Use item to bring up the multi-item placement target and/or ghost image of the multi.
- Target location.
- Crash.

## Environment

* CrossUO version: v1.0.0 (276195a6)
* Operating System: macOS Sierra 10.12.6
* Server Info: RunUO (unknown version)
* Server Address: login.uoforever.com:2599
* Server Account Creation: auto-account

**Comment by Nirad** [comment]
Fixed in 9ef14c4857dd1acbf122b8750e606244547d66d2

**Comment by Nirad** [comment]
fixed
