### ISSUE TITLE
Crash when logging into character that is already logged in.

### ISSUE THREAD

**Issue by linxgws** [crossuo/crossuo#48]
## Description

Game crashes when attempting to login to a character that is already logged into the server on another game client.

## Repro steps

- Login to a character on a different client (example: Classic UO client with UOSteam assistant)
- Attempt to login to that same character via CrossUO client.
- Crash.

Expected behavior is that it should login successfully with the CrossUO client, and disconnect the other client that was previously connected.

## Environment

* CrossUO version: v1.0.0 (276195a6)
* Operating System: macOS Sierra 10.12.6
* Server Info: RunUO (unknown version)
* Server Address: login.uoforever.com:2599
* Server Account Creation: auto-account

**Comment by Nirad** [comment]
If you try to connect with Original client on a Login Character on another client what happen ?

**Comment by Nirad** [comment]
i am not able to reproduce your issue if you can add me the crossuo.log thx 
![image](https://user-images.githubusercontent.com/359353/52890939-81224a00-3155-11e9-9eb5-1283fa0800fe.png)

**Comment by Nirad** [comment]
We need news @linxgws plz ..

**Comment by linxgws** [comment]
I'll test this some more and update you on it shortly.

**Comment by fungos** [comment]
I did a lot of testing on my side here and couldn't reproduce either.
