### ISSUE TITLE
Expansion control feature

### ISSUE THREAD

**Issue by FiLoUs64** [crossuo/crossuo#53]
On sphere 56d when you want to restrict some feature from expansion, CrossUO don't restrict it as Classic Client.

AOS expansion

Feature setting on sphere :

//AOS expansion features
// FEATURE_AOS_UPDATE_A			01 // AOS Monsters, Map
// FEATURE_AOS_UPDATE_B			02 // Tooltip, Fightbook, Necro/paladin on creation, Single/Six char selection screen, Skills, Newer spellbook support
// FEATURE_AOS_POPUP			04 // PopUp Menus
// FEATURE_AOS_DAMAGE			08 // Show damage values above char head when deal/receive any damage
FeatureAOS=0

CrossUO don't manage correctly the restriction.

FeatureAOS=01 is supposed to only have monster and map support, on CrossUO you can create the paladin/necromancer

- Char creation with Necro/Paladin, on classic client you will have this message to restrict :

![image](https://user-images.githubusercontent.com/47130805/52913198-be87f400-3289-11e9-8946-898ccbcfe602.png)

CrossUO will permit the char creating also if AOS is disable on the emulator.

IF you block all AOS feature (FeatureAOS=0) and for other expansion like SE, I have this message 

![image](https://user-images.githubusercontent.com/47130805/52913269-6dc4cb00-328a-11e9-9f4c-d6cbe690e366.png)

and this message on sphere console : 

> 08:02:WARNING:3:Bad Login 16 (Character creation  blocked)

Also on Classic Client, when you restrict ML feature (elf race) you are not able to choose this race :

![image](https://user-images.githubusercontent.com/47130805/52913691-9ea6ff00-328e-11e9-9484-9e7590cf0e8a.png)

On CrossUO you get "Communication problem" and same warning on sphere console.

## Environment

* CrossUO version: 1.0.0 client version 7.0.74.72
* Operating System: e.g. Windows 10
* Server Info: sphere 56d nightly
* Server Address: ask for test server
* Server Account Creation: ask

**Comment by Nirad** [comment]
@FiLoUs64 take a look at 
[Prof.txt](https://github.com/crossuo/crossuo/files/2896532/Prof.txt)
