### ISSUE TITLE
ctrl + q not working properly

### ISSUE THREAD

**Issue by FiLoUs64** [crossuo/crossuo#55]
On Classic Client (and also old Orion version) when you press ctrl + q it will recall last thing you write. 

## Repro steps

Write something in Classic Client and press ctrl + q. 

On old Orion he keep in memory everything you write, so if you press ctrl + q it will rewrite everything that was written in order from new to last.

Commit was already done for that but it's not in parity with Classic Client and old Orion

[https://github.com/crossuo/crossuo/issues/8](url)

## Environment

* CrossUO version: 1.0.0
* Operating System:  Windows 10, OSX
* Server Info: Any

**Comment by Nirad** [comment]
Thx should be good last time a user said to me you don't have to press enter. this time I have test with original client to make it same.
