### ISSUE TITLE
Wrong tool tip positionnement on character status

### ISSUE THREAD

**Issue by FiLoUs64** [crossuo/crossuo#56]
## Description

When you pass your mouse on character status to check where is str, dex etc.. You have the wrong information on CrossUO.

CrossUO :

![image](https://user-images.githubusercontent.com/47130805/52917544-c57b2a80-32ba-11e9-936a-1f6b933d3797.png)

Classic Client : 

![image](https://user-images.githubusercontent.com/47130805/52917549-d5930a00-32ba-11e9-97de-45ae20d1eb61.png)

## Repro steps

Just compare with CrossUO and Classic Client

## Environment

* CrossUO version: 1.0.0
* Operating System: Windows 10, OSX
* Server Info: Sphere 56d nightly
* Server Address: Ask for testing in game

**Comment by Nirad** [comment]
i see on original client it's depend where you place your Character status Gump on the left tooltip will be at right and on the right tooltip will be at left

**Comment by Nirad** [comment]
![capture d ecran 2019-02-21 a 01 20 17](https://user-images.githubusercontent.com/359353/53147914-f9827400-3576-11e9-8dbc-2f667e8434e9.png)
Fixed
