### ISSUE TITLE
Functional macros not working (Options, Map, etc.)

### ISSUE THREAD

**Issue by jinh86** [crossuo/crossuo#60]
## Description

Even though creating new macros like "say" or "emote" something work, the standard ones that are made for the options (Options/Configuration, Map, Paperdoll, etc.) don't work. Accessing those gumps from the Paperdoll buttons works normally, is just the pre-set macros that don't really do anything.

## Repro steps

Just tried on both Windows and Mac, because at the start I thought it was a Mac issue (due to the different interpretation the client can give to ALT/OPTION), but it's confirmed on both versions so it's not a key issue.

## Environment

* CrossUO version: 1.0.1
* Operating System: Windows 10 Enterprise and Mac OS Mojave (issue on both versions)
* Server Info: Custom RunUO (based on 1.0 - client protocol 5.8.2b).
* Server Address: -
* Server Account Creation: -

**Comment by fungos** [comment]
As we fix this we should implement the missing default macros, here are all of them:
```
ALT+S
Open
Status

ALT+T
Open
Chat

ALT+B
Open
MageSpellbook

ALT+C
War/Peace

ALT+P
Open
Paperdoll

ALT+K
Open
Skills

ALT+J
Open
Journal

ALT+Q
Open
QuestLog

ALT+W
Open
SpellWeavingSpellbook

ALT+I
Open
Backpack

ALT+R
Open
Overview (minimap)

ALT+O
Open
Configuration

ALT+X
QuitGame

CTRL+B
Bow

CTRL+S
Salute

CTRL+ALT+SHIFT+Q
SaveDesktop
```

As users have already configured macro, these should be created automatically if there is no actual config (first run of a profile for example)

**Comment by Nirad** [comment]
Maybe need to check if we want to keep macro in de cuo format ....

**Comment by fungos** [comment]
Sure not. We must eliminate any .cuo file from existence. If you're willing to do, great and maybe it is best to start by it.

**Comment by Nirad** [comment]
yes but we need to keep cross compatibility or not ?

**Comment by fungos** [comment]
Yes, but that is easy: we try to load the new cfg, if it does not exists we try to load the cuo, Then when saving, we only save the cfg and it will never read the cuo again, and in a few releases we can just remove the cuo code.
