### ISSUE TITLE
Worldmap do not open (OSX)

### ISSUE THREAD

**Issue by FiLoUs64** [crossuo/crossuo#77]
When trying to open worldmap, nothing appears.

![Capture d’écran, le 2019-03-10 à 09 04 18](https://user-images.githubusercontent.com/47130805/54085341-8b2e0780-4313-11e9-87b6-a06ad3300505.png)

## Environment

* CrossUO version: Last Nightly build
* Operating System: e.g. OSX

**Comment by Nirad** [comment]
Yes World Map is a part of X:UO Assit

**Comment by Nirad** [comment]
@FiLoUs64 can you send me screen of Orion WorldMap ?
