### ISSUE TITLE
Cyrillic letters

### ISSUE THREAD

**Issue by Krubster** [crossuo/crossuo#79]
At prevous (before crossuo) versions of Orion it was possible to use cyrillic locale, now these letters dont appear on screen when I m trying to write something.

**Comment by fungos** [comment]
Which platform? If you try to copy-paste a Cyrillic text into the client, does it work?

Dev note:
SDL2 TextInput events needs a lot of work, look for `EvChar`.

**Comment by Krubster** [comment]
Windows. Copy-paste doesn't work too, but if some mobile was named with cyrillic letters(some other way) - the letters exist. Also all cyrillic letters displays as ??????? at object handles, but it seems to be font issue.
