### ISSUE TITLE
FPS drops on mobile appearance

### ISSUE THREAD

**Issue by Krubster** [crossuo/crossuo#80]
## Description

When a bunch of mobiles appear on screen -  a fps drop appears

## Repro steps

Tested with a bunch of mongbats in green zone. Added 10-15, then ran away and ran to them again. FPS dropped from 70 to 40.
In luna on Inceptum server: walking in bank from moongate causes fps drop

## Environment

* CrossUO version: 1.0.2 (built myself)
* Operating System:  Windows 7 64x
* Server Info: RunUO Custom
* Server Address: login.uogames.ru:2593
* Server Account Creation: auto-account
* Video: Nvidia GeForce 620m
* CPU: Core i5-3337U

**Comment by fungos** [comment]
Did you do the same test but with our released binary?

**Comment by Krubster** [comment]
Seems strange. I downloaded latest crossuo with launcher and now fps stays near 100 and runs smoother, but on freshly built client it stays near 60 and has lag spikes.

**Comment by fungos** [comment]
Are you sure you have it built in Release? Also, which MSVC version?

**Comment by Nirad** [comment]
Yes the probleme it's maybe the Debug build with more logging option turned on

**Comment by Krubster** [comment]
Yes, rebuilt it in Release mode and fps now stable, thx :+1:
