### ISSUE TITLE
New Mounts, Mounted animation missing

### ISSUE THREAD

**Issue by Dragorniak** [crossuo/crossuo#9]
## Description

New Mounts like Eowmu, are not visible when it's mounted, instead a normal horse appears 

## Environment

* CrossUO version: e.g. 1.2.0, build from code at master or commit hash
* Operating System: e.g. Windows 10, Windows 7, Ubuntu Linux, etc
* Server Info: sphere v0.99g, POL 100, RunUO 2.7, etc.
* Server Address: uo.server.com,2599
* Server Account Creation: auto-account, account creation url, etc.

**Comment by Nirad** [comment]
same as issue #1

**Comment by fungos** [comment]
@Dragorniak can you test this release for your case and confirm it fixes it?

https://github.com/crossuo/crossuo/releases/tag/Latest-nightly

**Comment by wuffl** [comment]
Testet with CrossUO beta v1.0.2 (6320d4dd) and sphereX
While _running_ in the body of a "primevil lich" death animations are playing.
While walking slowly/normal looks good.
Find some screenshots attached. Those were made while running.
![201923_1745](https://user-images.githubusercontent.com/21044194/53689226-6b19a980-3d51-11e9-881a-a2a69debf7e3.png)
![201923_1756](https://user-images.githubusercontent.com/21044194/53689227-6b19a980-3d51-11e9-90ad-604fa2856e20.png)
![201923_1757](https://user-images.githubusercontent.com/21044194/53689228-6b19a980-3d51-11e9-8fc3-06acaea86690.png)
![201923_1758](https://user-images.githubusercontent.com/21044194/53689229-6b19a980-3d51-11e9-9bf7-af348a8496f5.png)

**Comment by Nirad** [comment]
Thx for this

**Comment by wuffl** [comment]
I need to correct myself:
even while walking the animation is not correct. It's using the walking-warmode-animation. It looks like all sub-animations are shifted and mixed up in a weired way.

**Comment by fungos** [comment]
Some time ago a few mounts were fixed (https://github.com/crossuo/crossuo/commit/2e972f610586e24cbd3611f3345326d40599aca4)
